print("Reglas tres en raya")
print("1. El juego se juega en un tablero del 3×3.")
print("2. Los jugadores eligen un simbolo para jugar.")
print("3. Inicia el jugador 'X'")
print("4. Continua el jugador 'o' y asi sucesivamente")
print("5. No se puede jugar en una casilla ocupada.")
print("6. Gana el jugador que logre alinear tres simbolos en linea horizontal")
print("7. Si no hay más casllla disponible y no hay ganador es empate")